# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demitas2 < Formula
  desc "Wrapper for ecspresso that creates task definitions at run time."
  homepage "https://github.com/winebarrel/demitas2"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.1.9/demitas2_0.1.9_darwin_arm64.tar.gz"
      sha256 "408d2bb936fc1e1e97350ea8c0acf1fec8f58d7d673b70c2853f9d052f15ce54"

      def install
        bin.install 'dmts'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.1.9/demitas2_0.1.9_darwin_amd64.tar.gz"
      sha256 "479faef54569ae33b62de7df28eeb89c735dd704244130b6a66ef22b85d199fa"

      def install
        bin.install 'dmts'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.1.9/demitas2_0.1.9_linux_arm64.tar.gz"
      sha256 "c93557bbc42ae4a49474c0d2c6f83323ace150dd6e5d1cb13676abeccb070093"

      def install
        bin.install 'dmts'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.1.9/demitas2_0.1.9_linux_amd64.tar.gz"
      sha256 "97d279302ceb0d35bc4298777e6a16a9c53746ad24fc93e9d3240b6b3cf78e4d"

      def install
        bin.install 'dmts'
      end
    end
  end
end
