# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demitas2 < Formula
  desc "Wrapper for ecspresso that creates task definitions at run time."
  homepage "https://github.com/winebarrel/demitas2"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.3.2/demitas2_0.3.2_darwin_amd64.tar.gz"
      sha256 "35bc4a5368062bab51aa0d41d4011e23c7b3ca6f2a7805d3a88f333b13cdfa92"

      def install
        bin.install 'dmts'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.3.2/demitas2_0.3.2_darwin_arm64.tar.gz"
      sha256 "1b65fc9bf2cd9c1e7aefd8a3d67387543f07c023a696a91b222fb6a42a63eb5c"

      def install
        bin.install 'dmts'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.3.2/demitas2_0.3.2_linux_arm64.tar.gz"
      sha256 "0dd7dd1314ef7c8153d9773abb736281beb61108a965da244dd130e979c75915"

      def install
        bin.install 'dmts'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.3.2/demitas2_0.3.2_linux_amd64.tar.gz"
      sha256 "753dc503b346f19effd81f4f7e11f18717b10efb5f4654785f918217f76c0b6b"

      def install
        bin.install 'dmts'
      end
    end
  end
end
