# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demitas2 < Formula
  desc "Wrapper for ecspresso that creates task definitions at run time."
  homepage "https://github.com/winebarrel/demitas2"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.1.5/demitas2_0.1.5_darwin_arm64.tar.gz"
      sha256 "a96a5d9a2b4119d7eb707771c52d65564090b2a7a794218b5d8ec2eb5ce164eb"

      def install
        bin.install 'dmts'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.1.5/demitas2_0.1.5_darwin_amd64.tar.gz"
      sha256 "78791861fae18f264aa0e97e04d2afe9ebd94573eaa5865ff78f7134ddbfccf7"

      def install
        bin.install 'dmts'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.1.5/demitas2_0.1.5_linux_arm64.tar.gz"
      sha256 "eb22cd7509bfab204353694b6e744ddc129d0b6fe8b811eedddf976b43115b17"

      def install
        bin.install 'dmts'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/demitas2/releases/download/v0.1.5/demitas2_0.1.5_linux_amd64.tar.gz"
      sha256 "e1b8e7d6c7f42fb66d35094feed7fc132bf0ccdc112ef100c343f053518044c9"

      def install
        bin.install 'dmts'
      end
    end
  end
end
